name: Build and Push Docker Images to AWS ECR

on:
  push:
    branches: # the branch to be deployed
      - main
  # pull_request:
  #   branches:
  #     - main
jobs:
  build_middleware:
    name: Build middleware Image
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push middleware image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: risingwave-node
          IMAGE_NAME: risingwave-node
          RUN_NUMBER: ${{ github.run_number }}
        run: |
          docker build -t $IMAGE_NAME ./
          docker tag $IMAGE_NAME $ECR_REGISTRY/$ECR_REPOSITORY:$RUN_NUMBER
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$RUN_NUMBER
